// This file is generated by Astro DB
declare module 'astro:db' {
	export const Link: import("@astrojs/db/runtime").Table<
		"Link",
		{"id":{"type":"number","schema":{"unique":false,"deprecated":false,"name":"id","collection":"Link","primaryKey":true}},"title":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"title","collection":"Link","primaryKey":false,"optional":false}},"url":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"url","collection":"Link","primaryKey":false,"optional":false}},"date":{"type":"date","schema":{"optional":false,"unique":false,"deprecated":false,"name":"date","collection":"Link","default":{"__serializedSQL":true,"sql":"CURRENT_TIMESTAMP"}}},"isRead":{"type":"boolean","schema":{"optional":false,"unique":false,"deprecated":false,"name":"isRead","collection":"Link"}},"upvoteNum":{"type":"number","schema":{"unique":false,"deprecated":false,"name":"upvoteNum","collection":"Link","primaryKey":false,"optional":false}}}
	>;
}
